<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
  
    <Actions category="Scripts">
        <text>Canvas Expander: Canvas operations</text>
        
        <Action name="pykrita_canvas_expander_default">
        <toolTip>Resize the canvas to fit all paint layers and viewport (infinite canvas).</toolTip>
        <statusTip>Resize the canvas to fit all paint layers and viewport (infinite canvas).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_active">
        <toolTip>Resize the canvas to fit the current layer.</toolTip>
        <statusTip>Resize the canvas to fit the current layer.</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_selected_layers">
        <toolTip>Resize the canvas to fit all selected layer(s).</toolTip>
        <statusTip>Resize the canvas to fit all selected layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_paint_layers">
        <toolTip>Resize the canvas to fit all paint layer(s).</toolTip>
        <statusTip>Resize the canvas to fit all paint layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_viewport">
        <toolTip>Resize the canvas to match the viewport (fast crop).</toolTip>
        <statusTip>Resize the canvas to match the viewport (fast crop).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_selection">
        <toolTip>Resize the canvas to fit the current selection.</toolTip>
        <statusTip>Resize the canvas to fit the current selection.</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_scale_to_zoom">
        <toolTip>Scale the image by current zoom level.</toolTip>
        <statusTip>Scale the image by current zoom level.</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
    </Actions>
  
    <Actions category="Scripts">
        <text>Canvas Expander: Layer visibility operations</text>
        
        <Action name="pykrita_canvas_expander_layer_toggle_selected">
        <toolTip>Toggle visibility for selected layer(s).</toolTip>
        <statusTip>Toggle visibility for selected layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_blue">
        <toolTip>Toggle visibility for all blue colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all blue colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_green">
        <toolTip>Toggle visibility for all green colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all green colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_yellow">
        <toolTip>Toggle visibility for all yellow colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all yellow colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_orange">
        <toolTip>Toggle visibility for all orange colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all orange colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_brown">
        <toolTip>Toggle visibility for all brown colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all brown colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_red">
        <toolTip>Toggle visibility for all red colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all red colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_purple">
        <toolTip>Toggle visibility for all purple colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all purple colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_toggle_grey">
        <toolTip>Toggle visibility for all grey colored layer(s).</toolTip>
        <statusTip>Toggle visibility for all grey colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_selected">
        <toolTip>Toggle isolate selected layer(s).</toolTip>
        <statusTip>Toggle isolate selected layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_blue">
        <toolTip>Toggle isolate all blue colored layer(s).</toolTip>
        <statusTip>Toggle isolate all blue colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_green">
        <toolTip>Toggle isolate all green colored layer(s).</toolTip>
        <statusTip>Toggle isolate all green colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_yellow">
        <toolTip>Toggle isolate all yellow colored layer(s).</toolTip>
        <statusTip>Toggle isolate all yellow colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_orange">
        <toolTip>Toggle isolate all orange colored layer(s).</toolTip>
        <statusTip>Toggle isolate all orange colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_brown">
        <toolTip>Toggle isolate all brown colored layer(s).</toolTip>
        <statusTip>Toggle isolate all brown colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_red">
        <toolTip>Toggle isolate all red colored layer(s).</toolTip>
        <statusTip>Toggle isolate all red colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_purple">
        <toolTip>Toggle isolate all purple colored layer(s).</toolTip>
        <statusTip>Toggle isolate all purple colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
        <Action name="pykrita_canvas_expander_layer_isolate_grey">
        <toolTip>Toggle isolate all grey colored layer(s).</toolTip>
        <statusTip>Toggle isolate all grey colored layer(s).</statusTip>
        <activationFlags>1</activationFlags>
        </Action>
        
    </Actions>
  
</ActionCollection>
